### ISSUE TITLE
Layout Navbar

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#1]
## Value Statement
As a user of the app, I want to have a useful navigation which takes me to the different landing pages of the app.
![navbar](https://user-images.githubusercontent.com/79857938/116115317-8aef5280-a6ba-11eb-8439-afc143f80605.png)

## Acceptance Criteria
- [x] navbar should be placed in the footer
- [x] navbar should always be visible
- [x] it should be responsive

## Tasks
- [x] create the navbar
- [x] import icons
- [x] create components
- [x] make them responsive
- [x] add css
