### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#1]
## Basic structure of the app
As a **traveller** I need **a clear stucture to navigate through the app** so that **my data is organized**.

## Description 
![Screenshot 2021-04-26 at 09 29 01](https://user-images.githubusercontent.com/79857938/116045060-eea15d80-a671-11eb-89eb-1e1336ce23e1.png)

## Acceptance criteria
- [ ] navigate through the app

## Tasks
- [ ] add React
- [ ] add components folder
- [ ] add images folder

## Size
medium
