### ISSUE TITLE
Edit button

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#12]
## Value Statement
As a user I want to edit my data in case I find more information about my trip that I want to keep in the app.

## Description
![Edit button](https://user-images.githubusercontent.com/79857938/116805447-f99f3680-ab26-11eb-8b78-c94dc468cb4f.png)

## Acceptance Criteria
- [x] edit button which edits the content

## Tasks
- [x] edit button should change the content
- [x] save the new content 

## Size
medium
