### ISSUE TITLE
Create the form

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#2]
## Value statement
As a user of the app I will be able to enter notes to my app.

![form](https://user-images.githubusercontent.com/79857938/116065002-d6880900-a686-11eb-8982-ea59a9716043.png)

## Acceptance criteria 
- [x] user should be able to put input in the text areas
- [x] unfolding text input

## Tasks
- [x] add text area fields for destination, activities, restaurants, notes
- [x] add already placeholder for the photos
- [x] add unfolding function
- [x] add styling to it
