### ISSUE TITLE
Upload of multiple photos and slide through in the gallery

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#21]

**Comment by yvlange** [comment]
## Value Statement
The user should be able to upload multiple pictures to a trip.

## Acceptance Criteria
- [ ] upload another picture from the edit page
- [ ] view that picture on the updated trip page

## Tasks
- [ ] let all pictures show on the trip page

## Size
large
