### ISSUE TITLE
Add weather api

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#22]
## Value Statement
In order to have a better travel experience, the user should be able to check the weather in the desired destination.

## Description
The weather is shown in the saved trip.

## Acceptance Criteria
- [x] fetch correct data from the weather api
- [x] get icon for better UX

## Tasks 
- [x] fetch correct data from the weather api
- [x] get icon for better UX
- [x] adjust css

## Size
small

**Comment by yvlange** [comment]
## Value Statement
In order to have a better travel experience, the user should be able to check the weather in the desired destination.

## Description
The weather is shown in the saved trip.

## Acceptance Criteria
- [ ] fetch correct data from the weather api
- [ ] get icon for better UX

## Tasks 
- [ ] fetch correct data from the weather api
- [ ] get icon for better UX
- [ ] adjust css

## Size
small
