### ISSUE TITLE
LocalStorage

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#23]
## Value Statement
As a user, I want to save my trips to the app in order to see them anytime I want, change them or remove them from the app.

## Acceptance Criteria
- [x] save trip to localStorage
- [x] edit trip in localStorage
- [x] remove trip from localStorage

## Tasks
- [x] create function to add trips to localStorage
- [x] create function to get a single trip from localStorage
- [x] create function to edit a single trip
- [x] create function to remove a single trip

## Size
large

**Comment by yvlange** [comment]
## Value Statement
As a user, I want to save my trips to the app in order to see them anytime I want, change them or remove them from the app.

## Acceptance Criteria
- [ ] save trip to localStorage
- [ ] edit trip in localStorage
- [ ] remove trip from localStorage

## Tasks
- [ ] create function to add trips to localStorage
- [ ] create function to get a single trip from localStorage
- [ ] create function to edit a single trip
- [ ] create function to remove a single trip

## Size
large
