### ISSUE TITLE
Upload photos

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#3]
## Value Statement
As a user, I want to upload photos that I took that help me planning the trip, so I have all information for this trip in one page.

## Description
![Screenshot 2021-04-26 at 11 59 00](https://user-images.githubusercontent.com/79857938/116066119-fff56480-a687-11eb-9217-e937b43c8a1d.png)

## Acceptance criteria
- [x] photo area shouold be clickable
- [x] add photos from device
- [x] save these pictures

## Tasks
- [x] add photo area
- [x] check api (cloudinary/filestack)
- [x] save input and store it in localStorage

## Size 
large
