### ISSUE TITLE
Create saved trip page

### ISSUE THREAD

**Issue by yvlange** [yvlange/capstone-travelist#4]
## Value Statement
As a user of this app, I like to have one page which holds all the information saved for a trip.

## Description
![Screenshot 2021-04-26 at 12 16 33](https://user-images.githubusercontent.com/79857938/116067244-44cdcb00-a689-11eb-9c56-33a761820db2.png)

## Acceptance Criteria
- [x] should show same text areas where the input of page "Add" can go

## Tasks
- [x] create the layout of the page
- [x] add unfolding functionality
- [x] add css 

## Size
medium
